### ISSUE TITLE
I cannot get seatable working. I would love to try it out.

### ISSUE THREAD

**Issue by cocoonkid** [seatable/seatable#119]
I run via docker-compose

```
version: "3"

services:
  db:
    image: mariadb:10.4
    container_name: seatable-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Requested, set the root's password of MySQL service.
      MYSQL_LOG_CONSOLE: "true"
    volumes:
      - ${SEATABLE_DB_PATH}:/var/lib/mysql # Requested, specifies the path to MySQL data persistent store.


  memcached:
    image: memcached:1.5.6
    container_name: seatable-memcached
    entrypoint: memcached -m 256


  redis:
    image: redis:5.0.7
    container_name: seatable-redis

  seatable:
    image: seatable/seatable:latest
    container_name: seatable
    volumes:
      - ${SEATABLE_DATA_PATH}:/shared # Requested, specifies the path to Seafile data persistent store.
    environment:
      DB_HOST: ${DB_HOST}
      DB_ROOT_PASSWD: ${MYSQL_ROOT_PASSWORD} # Requested, the value shuold be root's password of MySQL service.
      SEATABLE_SERVER_LETSENCRYPT: "True" # Default is False. Whether to use let's encrypt certificate.
      SEATABLE_SERVER_HOSTNAME: tables.prosanhive.com # Specifies your host name.
      TIME_ZONE: Etc/UTC # Optional, default is UTC. Should be uncomment and set to your local time zone.
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - db
      - memcached
      - redis


#networks:
 # seatable-net:
      
networks:
    default:
       external:
         name: webproxy
```
my .env
```
SEATABLE_DATA_PATH=/home/ubuntu/docker-volumes/seatable_data/config
SEATABLE_DB_PATH=/home/ubuntu/docker-volumes/seatable_data/db


DOMAINS=tables.somedomain.com

MAIN_DOMAIN=somedomain.com

LETSENCRYPT_EMAIL=somemail

NETWORK=webproxy

MYSQL_ROOT_PASSWORD=somepw
DB_HOST=db
```

All I get are these errors in the log but I doublechecked and the data inside the containers is where it is supposed to be.

Could this be a permission Issue?

```

cp: cannot stat '/opt/seatable/seatable-server-latest/dtable-web/media/avatars/*': No such file or directory
nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:25

[09/22/2020 01:14:41 PM] seafile-session.c(274): Failed to open template dir /opt/seatable/seafile-data/library-template: Error opening directory “/opt/seatable
/seafile-data/library-template”: No such file or directory.

```

I started the service as well. But to no avail. I am using  https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion which works with all my services without any Issues and its logs don't convey anything either.
