### ISSUE TITLE
Loading base page fails with JS error

### ISSUE THREAD

**Issue by ardoi** [seatable/seatable#123]
After creating a test base and opening it (`/workspace/1/dtable/test/`) I get an endlessly spinning loader and an error in the console:
```
 dtable-store.js:24792 Uncaught (in promise) Error: TypeError: Cannot read property 'forEach' of undefined
    at e.<anonymous> (dtable-store.js:24792)
    at c (dtable-store.js:26417)
    at Generator._invoke (dtable-store.js:26397)
    at Generator.E.forEach.e.<computed> [as next] (dtable-store.js:26454)
    at c (dtable-store.js:26417)
    at t (dtable-store.js:26466)
    at dtable-store.js:26472
```
My `docker_compose.yml` is:

```
version: '2.0'
services:
  db:
    image: mariadb:10.4
    container_name: seatable-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nottherealpassword  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seatable/mysql-data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seatable-net

  memcached:
    image: memcached:1.5.6
    container_name: seatable-memcached
    entrypoint: memcached -m 256
    networks:
      - seatable-net

  redis:
    image: redis:5.0.7
    container_name: seatable-redis
    networks:
      - seatable-net
          
  seatable:
    image: seatable/seatable:latest
    container_name: seatable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/seatable/seatable-data:/shared  # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=nottherealpassword  # Requested, the value shuold be root's password of MySQL service.
      - SEATABLE_SERVER_LETSENCRYPT=False # Default is False. Whether to use let's encrypt certificate.
      - SEATABLE_SERVER_HOSTNAME=my.seatable.local# Specifies your host name.
      - TIME_ZONE=Etc/UTC # Optional, default is UTC. Should be uncomment and set to your local time zone.
    depends_on:
      - db
      - memcached
      - redis
    networks:
      - seatable-net

networks:
  seatable-net:
```
