### ISSUE TITLE
Configuration of dtable_server_config.json in conflict when using HAProxy + SSL

### ISSUE THREAD

**Issue by mdartic** [seatable/seatable#25]
We have configured a seatable server with a HAProxy + docker stack : 

Here is the docker stack config : 

```
version: '3.7'
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - mysql-data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    secrets:
      - mysql_root_password

  memcached:
    image: memcached:1.5.6
    entrypoint: memcached -m 256

  redis:
    image: redis:5.0.7
          
  seatable:
    image: seafileltd/seatable:0.9.7
    ports:
      - "8083:80"
    volumes:
      - seatable-data:/shared  # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=/run/secrets/mysql_root_password  # Requested, the value shuold be root's password of MySQL service.
      - SEATABLE_SERVER_LETSENCRYPT=False # Default is False. Whether to use let's encrypt certificate.
      - SEATABLE_SERVER_HOSTNAME=staging-asip-seatable.makina-corpus.net # Specifies your host name.
      - TIME_ZONE=Europe/Paris # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=******
      - SEAFILE_ADMIN_PASSWORD=******
    depends_on:
      - db
      - memcached
      - redis
    secrets:
      - mysql_root_password

volumes:
  mysql-data:
  seatable-data:

secrets:
  mysql_root_password:
    file: secrets/mysql_root_password
```

The seatable docker is configured to be used in http (`SEATABLE_SERVER_LETSENCRYPT` to `False`).
It is served through HAProxy, who managed SSL, for the domain "staging-asip-seatable.makina-corpus.net/".

We think we have found a issue in the `/opt/seatable/conf/dtable_web_settings.py` : 

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'db',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '******',
        'NAME': 'dtable_db',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
        'LOCATION': 'memcached',
    },
    'locmem': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}
COMPRESS_CACHE_BACKEND = 'locmem'

# for dtable-server
DTABLE_PRIVATE_KEY = '^@i2!u^o+#58$)26t!b57fz8vlp901_0f=e1$w0js9z@2b4w2#'
DTABLE_SERVER_URL = 'http://staging-asip-seatable.makina-corpus.net/dtable-server/'
DTABLE_SOCKET_URL = 'http://staging-asip-seatable.makina-corpus.net/'

# for dtable-web
DTABLE_WEB_SERVICE_URL = 'http://staging-asip-seatable.makina-corpus.net/'

# for seaf-server
FILE_SERVER_ROOT = 'http://staging-asip-seatable.makina-corpus.net/seafhttp/'
```

When you try to open a database or forms, from the URL `https://staging-asip-seatable.makina-corpus.net/`, you go to `https://staging-asip-seatable.makina-corpus.net/workspace/1/dtable/Another database/`.
Your browser will try to GET a file on the http URL (not the https): 

![image](https://user-images.githubusercontent.com/2027964/79238271-79e8f000-7e6f-11ea-9cf9-f639d52de369.png)

We solve this issue by setting all URLs in `dtable_web_settings.py` to `https`.

By testing one by one, I can say that both DTABLE_SERVER_URL and DTABLE_SOCKET_URL vars need to be in https for the browser, to avoid the `mixed active content` message.

I don't know if DTABLE_WEB_SERVICE_URL and FILE_SERVER_ROOT are used in the browser, but I changed them to https too.

Have we made a mistake during the configuration of seatable ?
If not, could you make this configuration a way to use seatable ?

Thank you
