### ISSUE TITLE
Blank page when clicking on table

### ISSUE THREAD

**Issue by dnacore88** [seatable/seatable#3]
Using docker-compose.yml file, the server (0.9.3) started successfully and I managed to login then create a table. Upon clicking the table only blank page is shown. Then I try running the docker-compose.yml file on another server and the result is the same blank page when clicking the created table(s).

Everything seems normal on docker-compose logs no error or anything suspicious. I change the port as follow:

```
version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seatable-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seatable/mysql-data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seatable-net

  memcached:
    image: memcached:1.5.6
    container_name: seatable-memcached
    entrypoint: memcached -m 256
    networks:
      - seatable-net

  redis:
    image: redis:5.0.7
    container_name: seatable-redis
    networks:
      - seatable-net

  seatable:
    image: seafileltd/seatable:0.9.3
    container_name: seatable
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - /opt/seatable/seatable-data:/shared  # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=mypassword  # Requested, the value shuold be root's password of MySQL service.
      - SEATABLE_SERVER_LETSENCRYPT=False # Default is False.Whether to use let's encrypt certificate.
      - SEATABLE_SERVER_HOSTNAME=192.168.49.8 # Specifies your host name if https is enabled
      - TIME_ZONE=Etc/UTC # Optional, default is UTC. Should be uncomment and set to your local time zone.
    depends_on:
      - db
      - memcached
      - redis
    networks:
      - seatable-net

networks:
  seatable-net:
```
Is there anything that I must configure further?

Edit: adding server version
