### ISSUE TITLE
How to Setup Seatable in Local Machine ?

### ISSUE THREAD

**Issue by aswinmohanme** [seatable/seatable#35]
I have followed this guide : https://docs.seatable.io/published/seatable-manual/docker/ce-edition/Deploy%20SeaTable-ce%20with%20Docker.md and have reached until starting the server. The commands execute just fine, but I do not know how to access the site running on local machine.

This is my docker file 
```
version: '2.0'
services:
  db:
    image: mariadb:10.4
    container_name: seatable-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamshandr  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seatable/mysql-data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seatable-net

  memcached:
    image: memcached:1.5.6
    container_name: seatable-memcached
    entrypoint: memcached -m 256
    networks:
      - seatable-net

  redis:
    image: redis:5.0.7
    container_name: seatable-redis
    networks:
      - seatable-net
          
  seatable:
    image: seafileltd/seatable:0.9.5
    container_name: seatable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/seatable/seatable-data:/shared  # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=iamshandr  # Requested, the value shuold be root's password of MySQL service.
      - SEATABLE_SERVER_LETSENCRYPT=True # Default is False. Whether to use let's encrypt certificate.
      - SEATABLE_SERVER_HOSTNAME=192.168.49.8 # Specifies your host name.
      - TIME_ZONE=Etc/UTC # Optional, default is UTC. Should be uncomment and set to your local time zone.
    depends_on:
      - db
      - memcached
      - redis
    networks:
      - seatable-net

networks:
  seatable-net:

```
